---
- name: Configure fstab
  ansible.builtin.template:
    dest: /etc/fstab
    owner: root
    group: root
    mode: "0644"
    src: fstab.j2
   # notify: fstab_update

- name: Create additional mount directories
  when:
    - fstab_create_additional_dirs
    - item.target != "none"
  ansible.builtin.file:
    path: "{{ item.target }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ fstab_mounts }}"
  # listen: fstab_update

- name: Systemd reload-daemon
  when: ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    daemon_reload: true
  # listen: fstab_update

- name: Run mount all
  when:
    - fstab_reload
    - fstab_reload_method == "mount"
  ansible.builtin.shell:
    cmd: "/usr/bin/mount -a"
  # listen: fstab_update
  # args:
  #   warn: false

# - name: Run mount 
#   ansible.posix.mount:
#     path: "{{ item.target }}"
#     state: ephemeral
#   loop: "{{ fstab_mounts }}"
